### ISSUE TITLE
[食堂] 英文菜单显示

### ISSUE THREAD

**Issue by SeakyLuo** [a211212abc/GoGauchoIssue#21]
菜名太长 一行不够显示

**Comment by a211212abc** [comment]
我可以加个判断 太长的就不显示么 @SeakyLuo

**Comment by SeakyLuo** [comment]
你是来搞笑的吗

**Comment by a211212abc** [comment]
暂时不会修复 欢迎随时reopen这个issue

**Comment by SeakyLuo** [comment]
修复这个真的很难吗……

**Comment by a211212abc** [comment]
是的 因为高度是固定的 文字也是单行显示的 我没法让他自动换行 也很难计算高度

**Comment by SeakyLuo** [comment]
没让你自动换行啊……比如缩小一丢丢字体，或者在这行上滑动一下然后菜名就会滚动显示这样（感觉很难，逃
