### ISSUE TITLE
[食堂] MenuSection改进

### ISSUE THREAD

**Issue by SeakyLuo** [a211212abc/GoGauchoIssue#22]
最上面的lunch dinner栏换个深一点的颜色 不然不好认
被你吃掉的那几栏可以加在最上面的lunch dinner后面
也可以跟华丽的分割线一样夹在菜里面

**Comment by a211212abc** [comment]
你觉得现在这样还需要变深颜色吗 或者用背景颜色来表示现在开没开门？或者用时间文字颜色表示现在是不是开门？你怎么看@SeakyLuo

**Comment by a211212abc** [comment]
以后或许可以加个动画再

**Comment by SeakyLuo** [comment]
现在这个问题可以缓缓 你加了营业时间就暂时不用担心有没有开门的问题了

**Comment by SeakyLuo** [comment]
显示bright meal这种次级菜单 不然有菜会重复显示

**Comment by a211212abc** [comment]
啊？

**Comment by a211212abc** [comment]
被 @SeakyLuo 通过调整服务器端解决
