### ISSUE TITLE
[课表] 小屏幕显示问题

### ISSUE THREAD

**Issue by a211212abc** [a211212abc/GoGauchoIssue#36]

**Comment by SeakyLuo** [comment]
请照顾一下iPad用户谢谢
还有我的二维码错位（iPad）
扫描那个按钮应该按一下弹出2个小按钮
一个扫描 一个我的课表的二维码

**Comment by SeakyLuo** [comment]
课标时间改成am pm啥的

**Comment by a211212abc** [comment]
微信就没有蹦两个按钮 我觉得我的二维码还可以从菜单进比较好 或者在二维码扫描界面的navigation bar价格按钮？ 然后再来个3D touch的快捷进入 你怎么看@SeakyLuo

**Comment by SeakyLuo** [comment]
我的意思就是 扫描跟我的二维码要分开 就行

**Comment by SeakyLuo** [comment]
你要3D touch不如先把基础的先做好（逃

**Comment by a211212abc** [comment]
不用逃 可是分开应该放在哪合适 按你说的做个下拉菜单不大合适吧（其实是不好做 还有其他办法么 放在设置还是扫码的右上角 还是both

**Comment by a211212abc** [comment]
多个问题放进多个issue...你咋还一口气说完了
